implement api with react query
Niki-Ku/basic-architecture-project pull request #23
Opened 2024-11-19 22:19 UTC by Niki-Ku

Integrate TMDB api with react query.

2024-11-20 09:02 UTC, YuriiSkyba1 requested changes

2024-11-20 09:02 UTC, YuriiSkyba1 commented on src/pages/HomePage/HomePage.tsx
> +  const { data } = useQuery(['data', page], testFetch, {refetchOnWindowFocus: false});
```
const { data, error, isLoading } = useQuery(['data', page], testFetch, {
  refetchOnWindowFocus: false,
});

if (isLoading) return <p>Loading...</p>;
if (error) return <p>Error fetching data: {error.message}</p>;
```
обробка помилок

2024-11-20 09:02 UTC, YuriiSkyba1 commented on src/pages/HomePage/HomePage.tsx
> +          {data?.results.map((d:any) => (
<div className="flex w-full overflow-auto">
  {data?.results?.length > 0 ? (
    data.results.map((d: прибери any) => (
      <img
      />
    ))
  ) : (
    <p>No data available</p>
  )}
</div>

2024-11-20 09:02 UTC, YuriiSkyba1 commented on src/pages/HomePage/HomePage.tsx
> +        <br />
шось так багато br
спробуй марджинами падінгами

2024-11-20 09:02 UTC, YuriiSkyba1 commented on src/pages/HomePage/HomePage.tsx
> +  const options = {
винесиі і добав константи для ключів
export const fetchUpcomingMovies = (page: number) => ({
  method: 'GET',
  url: `${API_BASE_URL}/movie/upcoming`,
  params: { language: 'en-US', page: page.toString() },
  headers: {
    accept: 'application/json',
    Authorization: `Bearer ${API_KEY}`,
  },
});

2024-11-20 09:02 UTC, YuriiSkyba1 commented on src/pages/HomePage/HomePage.tsx
> +  const options = {
потім const options = fetchUpcomingMovies(page);

2024-11-20 09:02 UTC, YuriiSkyba1 commented on src/pages/HomePage/HomePage.tsx
>      const snapshot = await getDocs(colRef);
any прибери і додай try catch

2024-11-21 10:18 UTC, Niki-Ku commented on src/pages/HomePage/HomePage.tsx
> +        <br />
ці br - вони тимчасові, просто для більш зручного вигляду. Ця сторінка буду кардинально перероблена в майбутньому

2024-11-21 10:21 UTC, Niki-Ku commented on src/pages/HomePage/HomePage.tsx
> +          {data?.results.map((d:any) => (
![Знімок екрана 2024-11-21 121920](https://github.com/user-attachments/assets/49c8d3af-f7a3-48df-b758-12d541ad2471)

TypeScript не пропускає без any. Хоче якось типізувати

2024-11-21 10:44 UTC, YuriiSkyba1 commented on src/pages/HomePage/HomePage.tsx
> +          {data?.results.map((d:any) => (
потрібно додати інтерфейс для data
```
interface Film {
  title: string;
  poster_path: string;
}
const { data } = useQuery<{ results: Film[] }>(['data', page], testFetch, { refetchOnWindowFocus: false });
```

2024-11-21 12:40 UTC, YuriiSkyba1 approved these changes

2024-11-21 12:53 UTC, merged